name: Release Build JQ

on:
  push:
    paths-ignore:
      - "*.md"
      - "compose.*"
    branches:
      - "jq"

env: 
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      
      - if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends musl-tools
 
      - name: Versions
        id: version
        run: echo "VERSION=$(cargo metadata --format-version 1 --no-deps | jq .packages[0].version -r | sed 's/^/v/')" >> "$GITHUB_OUTPUT"

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package release
        run: tar czf redlib-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release/ redlib

      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: ${{ steps.version.outputs.VERSION }} - ${{ github.event.head_commit.message }}
          draft: true
          files: |
            redlib-${{ matrix.target }}.tar.gz
          body: |
            - ${{ github.event.head_commit.message }} ${{ github.sha }}
          generate_release_notes: true
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # -
      #   name: Login to Quay.io Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.QUAY_USERNAME }}
      #     password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.target }}
          labels: ${{ steps.meta.outputs.labels }}
          #outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          file: Dockerfile.jq
          build-args: TARGET=${{ matrix.target }}

  # merge:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #   steps:
  #     -
  #       name: Download digests
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: digests
  #         path: /tmp/digests
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     -
  #       name: Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ${{ env.REGISTRY_IMAGE }}
  #         tags: |
  #           type=sha
  #           type=raw,value=latest,enable={{is_default_branch}}
  #     -
  #       name: Login to Quay.io Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: quay.io
  #         username: ${{ secrets.QUAY_USERNAME }}
  #         password: ${{ secrets.QUAY_ROBOT_TOKEN }}
  #     -
  #       name: Create manifest list and push
  #       working-directory: /tmp/digests
  #       run: |
  #         docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
  #           $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

  #     - name: Push README to Quay.io
  #       uses: christian-korneck/update-container-description-action@v1
  #       env:
  #         DOCKER_APIKEY: ${{ secrets.APIKEY__QUAY_IO }}
  #       with:
  #         destination_container_repo: quay.io/redlib/redlib
  #         provider: quay
  #         readme_file: 'README.md'

  #     -
  #       name: Inspect image
  #       run: |
  #         docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}


